spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kakaobank?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: test1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: ture

server:
  port: 8081